language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements/base.txt"
# before runnning the tests
before_script: "export SECRET_KEY='dnqsj22jdv9wjsldfub9'"
# command to run tests
script: "python manage.py test --settings=jmad.settings.base"
