language: python
python:
  - "3.3"
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements/ci.txt"
# before runnning the tests
before_script: "export SECRET_KEY='dnqsj22jdv9wjsldfub9'"
# command to run tests
script: 
 - "coverage run --source='.' manage.py test --settings=jmad.settings.base"
 - "coverage report --fail-under=85 --omit=*test*,*settings*"
